name: flu_england

on:
  schedule:
  - cron: "0 1 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3 # stops the file path from repeating the folder name
    
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"
        
    - name: Execute Python Script
      run: python flu_england.py
      
    - name: Commit files
      run: |      
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        timestamp=$(date -u)
        git add england_flu_data.csv
        git commit -am "Latest data: ${timestamp}" || exit 0  
        git push origin master
          
      env:
        REPO_KEY: ${{secrets.GITHUB_TOKEN}}
        username: github-actions
