name: flu_wales

on:
  schedule:
  - cron: "0 1 * * *"
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2 # stops the file path from repeating the folder name
    
    - name: Install Python dependencies
      uses: py-actions/py-dependency-install@v2
      with:
        path: "requirements.txt"
        
    - name: Execute Python Script
      run: python flu_wales.py
      
    - name: Commit files
      run: |
        git config user.name "${GITHUB_ACTOR}"
        git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest update: ${timestamp}" || exit 0
        git push
